spring:
  application.name: member-api
  data.rest.base-path: /api
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
eureka.client.service-url.defaultZone: http://localhost:8761/eureka